apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: b01-1-awusb
    domain: b01-1
    location: bl01c
  name: b01-1-awusb
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: b01-1-awusb
  template:
    metadata:
      labels:
        app: b01-1-awusb
        domain: b01-1
        location: bl01c
    spec:
      containers:
        - args:
            - infinity
          command:
            - sleep
          env:
            - name: LOCATION
              value: bl01c
            - name: DOMAIN
              value: b01-1
          image: ghcr.io/epics-containers/awusb-client:0.0.1b3
          imagePullPolicy: Always
          name: b01-1-awusb
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            # runAsUser: 1000
            # runAsGroup: 1000
          tty: true
          volumeMounts:
            - mountPath: /tmp/awusb_ipc
              name: awusb-ipc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 3
      volumes:
        - name: awusb-ipc
          hostPath:
            path: /tmp/awusb_ipc
            type: Directory
